---

- name: Ensure prerequisite packages are installed
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
    update_cache: true
  with_items:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release
